/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model.3d/scene.gltf --transform --types -o src/components/Model.tsx 
Files: public/model.3d/scene.gltf [25.32KB] > D:\Portofolio\Project Code\portofolio\v2.portofolio-raditzzz\src\components\scene-transformed.glb [2.46MB] (-9604%)
Author: 00004707 (https://sketchfab.com/0004707)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/holo-shapeshifter-5d581768fbe3425c8540e3ff329707bc
Title: Holo Shapeshifter
*/

import * as THREE from "three"
import React, { JSX } from "react"
import { useGraph } from "@react-three/fiber"
import { useGLTF, useAnimations } from "@react-three/drei"
import { GLTF, SkeletonUtils } from "three-stdlib"

type ActionName = "holy cow! an animation?!"

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_9: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = React.useRef<THREE.Group>(new THREE.Group())
  const { scene, animations } = useGLTF("/model.3d/scene-transformed.glb")
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.Material}
          skeleton={nodes.Object_9.skeleton}
          morphTargetDictionary={nodes.Object_9.morphTargetDictionary}
          morphTargetInfluences={nodes.Object_9.morphTargetInfluences}
          position={[2.882, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.5}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/model.3d/scene-transformed.glb")
